$(document).ready(function(){
    $('#reserveTable').click(function(){
        $('#reserve').modal("toggle");
        $('#reserve').modal("show");
    });
    $('#loginClicked').click(function(){
        $('#loginModal').modal("toggle");
        $('#loginModal').modal("show");
    });
    $('#mycarousel').carousel({interval:2000});
    $('#carouselButton').click(function(){
        if($('#carouselButton').children('span').hasClass('fa-pause'))
        {
            $('#mycarousel').carousel('pause');
            $('#carouselButton').children('span').removeClass('fa-pause');
            $('#carouselButton').children('span').addClass('fa-play');
        }
        else{
            $('#mycarousel').carousel('cycle');
            $('#carouselButton').children('span').removeClass('fa-play');
            $('#carouselButton').children('span').addClass('fa-pause');
        }
    });
});